# AI Model Settings
models:
  claude:
    model_name: "claude-3-5-haiku-20241022"
    temperature: 0.9
    max_tokens: 1000
    display_name: "Claude"

  chatgpt:
    model_name: "gpt-4o-mini"
    temperature: 0.9
    max_tokens: 1000
    display_name: "ChatGPT"

  gemini:
    model_name: "gemini-2.0-flash"
    temperature: 0.9
    max_tokens: 1000
    display_name: "Gemini"

  deepseek:
    model_name: "deepseek-chat"
    temperature: 0.9
    max_tokens: 1000
    display_name: "DeepSeek"

# System Settings
system:
  prompt: |
    これから大喜利をします。あなたは大喜利の回答者です。大喜利のルールは以下の通りです。
    1. 大喜利の回答は100文字以内で回答してください。
    2. 大喜利の回答は日本語で回答してください。
    3. 大喜利の回答はスマートで楽しいものを回答してください。
    4. 他の参加者の回答も会話に含めます。前の回答も考慮して回答をしてください。 